### PR TITLE
zuul: add auto-merge feature

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-On: https://github.com/wazo-platform/sf-config/pull/37
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/35

### CODE REVIEW

**Comment by fredericlepied** [comment]
remerge

**Comment by fredericlepied** [comment]
remerge

**Comment by sduthil** [comment]
remerge

**Comment by sduthil** [comment]
@fredericlepied do you have an idea why it failed?

**Comment by fredericlepied** [comment]
> @fredericlepied do you have an idea why it failed?

I think that's a restriction from github. we need to change the settings of the project and test again.

**Comment by sduthil** [comment]
remerge

**Comment by sduthil** [comment]
@fredericlepied you were right, it was because of the master branch protection.

**Pull request merged**
